name: dispatch

on:
  push:
  pull_request:

jobs:
  dispatch:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.DISPATCH_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: "jeremy-rifkin",
            repo: "wheatley-mirror",
            workflow_id: "mirror.yml",
            ref: "master"
          })
