name: test

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: dependencies
        run: npm i --dev
      - name: run test
        run: npm test
